// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package coeff_map_pkg;

    localparam COEFF_MAP_DATA_WIDTH = 32;
    localparam COEFF_MAP_MIN_ADDR_WIDTH = 3;
    localparam COEFF_MAP_SIZE = 'h4;

    typedef struct {
        logic [15:0] value;
    } coeff_rf__coeff_reg__val__out_t;

    typedef struct {
        logic value;
    } coeff_rf__coeff_reg__wr_en__out_t;

    typedef struct {
        logic [6:0] value;
    } coeff_rf__coeff_reg__wr_addr__out_t;

    typedef struct {
        logic [6:0] value;
    } coeff_rf__coeff_reg__max_coef_num__out_t;

    typedef struct {
        coeff_rf__coeff_reg__val__out_t val;
        coeff_rf__coeff_reg__wr_en__out_t wr_en;
        coeff_rf__coeff_reg__wr_addr__out_t wr_addr;
        coeff_rf__coeff_reg__max_coef_num__out_t max_coef_num;
    } coeff_rf__coeff_reg__out_t;

    typedef struct {
        coeff_rf__coeff_reg__out_t COEFF;
    } coeff_rf__out_t;

    typedef struct {
        coeff_rf__out_t COEFF_BLOCK;
    } coeff_map__out_t;
endpackage
